# IO设备控制命令
bool	 io_cmd_enable              # 使能控制
bool     io_cmd_lower_beam_headlamp  # 近光灯控制
bool     io_cmd_upper_beam_headlamp  # 远光灯控制
uint8	 io_cmd_turn_lamp            # 转向灯控制：0-关闭，1-左转，2-右转，3-双闪
bool     io_cmd_braking_lamp         # 刹车灯控制
bool     io_cmd_clearance_lamp       # 示廓灯控制
bool     io_cmd_fog_lamp             # 雾灯控制
bool	 io_cmd_speaker              # 扬声器控制
bool     io_cmd_disCharge            # 放电控制
